--- #YAML:1.0
name:               Nagios-Recover
version:            0.0.3
abstract:           Tries to recover a service executing a list of actions
author:
    - Francesc Guasch <frankie@etsetb.upc.edu>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    version:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
